### ISSUE TITLE
Install fails on Mac even after trouble shooting

### ISSUE THREAD

**Issue by phiweger** [nluhmann/BlastFrost#6]
Hi,

Did what you [suggested](https://github.com/pmelsted/bifrost#troubleshooting):

```bash
brew install brewsci/bio/bifrost
git clone https://github.com/nluhmann/BlastFrost
cd BlastFrost
mkdir build; cd build; cmake ..; make
./BlastFrost -h
# dyld: Library not loaded: libbifrost.dylib
#   Referenced from: .../BlastFrost/build/./BlastFrost
#  Reason: image not found
# Abort trap: 6

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib/
export PATH=$PATH:/usr/local/lib/
./BlastFrost -h
# fails again
```

Any ideas? A bioconda package as suggested in #5 would be awesome!

Kind regards

**Comment by GuillaumeHolley** [comment]
Hi there,

My apologies for the delay. I am not sure what is going on here but maybe a potential issue comes from the fact that you installed Bifrost using Brew while you installed BlastFrost from source. I'm not sure how Brew works but is is possible that it uses its own environment like Conda. Since BlastFrost is installed from source, it installs using a different environment (not the one of Brew) and that might be a possible reason to why the Bifrost library is not found. Could you try installing Bifrost from source and trying to reinstall BlastFrost afterwards? The Brew and Conda packages for Bifrost are fairly recent so we might need to adapt the install of BlastFrost to those packet managers.

Thank you,
Guillaume

**Comment by phiweger** [comment]
Thanks, I will try to create a docker container instead, circumventing the whole Mac issue :)
